version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest 
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - my-network  

  auth-service:
    image: auth-service-image
    container_name: auth-service-container
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    networks:
      - my-network  

  user-service:
    image: user-service-image
    container_name: user-service-container
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    networks:
      - my-network  

networks:
  my-network:

volumes:
  rabbitmq-data:
